### ISSUE TITLE
Does this module support peer routing?

### ISSUE THREAD

**Issue by guysv** [libp2p/js-libp2p-delegated-peer-routing#7]
[interface-peer-routing](https://github.com/libp2p/interface-peer-routing) states that this module implements the peer routing API, but I see no tests to confirm this. Also, I couldn't find a findPeer**s** method.

Who got it right?

**Comment by jacobheun** [comment]
The interface needs to be updated, it also doesn't include any exported tests yet, which also needs to be fixed. The state of this module is currently correct, you can see an example of it and content routing at https://github.com/libp2p/js-libp2p/tree/v0.24.4/examples/delegated-routing. The DHT also matches this implementation.

I created an issue so this gets tracked https://github.com/libp2p/interface-peer-routing/issues/18, thanks for bringing this up.

**Comment by achingbrain** [comment]
This has been fixed, https://www.npmjs.com/package/@libp2p/interface-peer-routing no longer references this module.
